services:
  postgres:
    image: postgres:latest
    container_name: order_db
    environment:
      POSTGRES_DB: "order_db"
      POSTGRES_USER: "jojo"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d/
  nats-streaming:
    image: nats-streaming:latest
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "6222:6222"